// ──────────────────────────────────────────────────────────────────
//  seed-sheets.mjs  — Injecte des données fictives dans Google Sheets
//  Usage : node scripts/seed-sheets.mjs
// ──────────────────────────────────────────────────────────────────

const API_URL = "https://script.google.com/macros/s/AKfycbzZQnoNI89_h9EMcq0v_yYhpawN6UaNTXPO84vCH6Asr2u1TzllNYUABM9rrk8C6pyQjQ/exec"

async function post(body) {
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "text/plain;charset=utf-8" },
    body: JSON.stringify(body),
    redirect: "follow",
  })
  const json = await res.json()
  return json
}

async function create(sheet, data) {
  const r = await post({ action: "create", sheet, data })
  const label = data["ID Famille"] ?? data["ID contact"]
  const nom   = data["Nom"] ? `${data["Prénom"] ?? ""} ${data["Nom"]}`.trim() : data["Nom"]
  if (r.success) {
    console.log(`  ✅  ${sheet.padEnd(8)} ${String(label).padEnd(8)} ${nom}`)
  } else {
    console.error(`  ❌  ${sheet} ${label} — ${JSON.stringify(r)}`)
  }
}

// ──────────────────────────────────────────────────────────────────
//  FAMILLES
// ──────────────────────────────────────────────────────────────────
const familles = [
  {
    "ID Famille":           "FAM002",
    "Nom":                  "Martin",
    "Adresse":              "14 rue des Acacias",
    "Code postal":          "44100",
    "Ville":                "Nantes",
    "Quartier QVP":         "Oui",
    "Téléphone":            "07 62 11 45 89",
    "Commentaires":         "Famille de 4, les deux parents très impliqués",
    "Contact principal - ID": "CONT011",
    "Membres - IDs":        "CONT010, CONT011, CONT012, CONT013",
  },
  {
    "ID Famille":           "FAM003",
    "Nom":                  "Benali",
    "Adresse":              "3 allée des Peupliers",
    "Code postal":          "44000",
    "Ville":                "Nantes",
    "Quartier QVP":         "Oui",
    "Téléphone":            "06 33 77 52 14",
    "Commentaires":         "Arrivée en France il y a 2 ans, motivation ++",
    "Contact principal - ID": "CONT014",
    "Membres - IDs":        "CONT014, CONT015, CONT016, CONT017",
  },
  {
    "ID Famille":           "FAM004",
    "Nom":                  "Nguyen",
    "Adresse":              "8 boulevard Michelet",
    "Code postal":          "44200",
    "Ville":                "Nantes",
    "Quartier QVP":         "Non",
    "Téléphone":            "07 88 23 04 61",
    "Commentaires":         "Mère seule, père non présent",
    "Contact principal - ID": "CONT018",
    "Membres - IDs":        "CONT018, CONT019",
  },
  {
    "ID Famille":           "FAM005",
    "Nom":                  "Diallo",
    "Adresse":              "27 rue du Breil",
    "Code postal":          "44300",
    "Ville":                "Nantes",
    "Quartier QVP":         "Oui",
    "Téléphone":            "06 51 88 39 72",
    "Commentaires":         "Grande famille, 3 enfants inscrits",
    "Contact principal - ID": "CONT021",
    "Membres - IDs":        "CONT020, CONT021, CONT022, CONT023, CONT024",
  },
  {
    "ID Famille":           "FAM006",
    "Nom":                  "Rousseau",
    "Adresse":              "5 impasse des Lilas",
    "Code postal":          "44000",
    "Ville":                "Nantes",
    "Quartier QVP":         "Non",
    "Téléphone":            "07 14 56 83 20",
    "Commentaires":         "Mère seule, disponible seulement le soir",
    "Contact principal - ID": "CONT025",
    "Membres - IDs":        "CONT025, CONT026, CONT027",
  },
  {
    "ID Famille":           "FAM007",
    "Nom":                  "Okafor",
    "Adresse":              "19 avenue de la Beaujoire",
    "Code postal":          "44300",
    "Ville":                "Nantes",
    "Quartier QVP":         "Oui",
    "Téléphone":            "06 70 44 19 35",
    "Commentaires":         "Famille nigériane arrivée récemment, anglophone",
    "Contact principal - ID": "CONT028",
    "Membres - IDs":        "CONT028, CONT029",
  },
]

// ──────────────────────────────────────────────────────────────────
//  CONTACTS
//  Parent  = "Oui" / "Non"
//  Bénéficiaire = "Oui" → suit des cours (a groupe, tests, assiduité)
//               = "Non" → inscrit ses enfants mais ne suit pas de cours
// ──────────────────────────────────────────────────────────────────
const contacts = [

  // ── FAM002 Martin ─────────────────────────────────────────────
  // Thomas Martin — père, NON bénéficiaire
  {
    "ID contact":   "CONT010",
    "Famille":      "Martin",
    "ID Famille":   "FAM002",
    "Nom":          "Martin",
    "Prénom":       "Thomas",
    "Parent":       "Oui",
    "Bénéficiaire": "Non",
    "N° de téléphone": "07 62 11 45 89",
    "WhatsApp":     "07 62 11 45 89",
    "Email":        "thomas.martin44@gmail.com",
    "Adresse":      "14 rue des Acacias",
    "Code postal":  "44100",
    "Ville":        "Nantes",
    "Date de naissance": "14/04/1980",
    "Groupe":       "",
    "Inscriptions": "",
    "Assiduité":    "",
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Nadia Martin — mère, OUI bénéficiaire (suit cours A1)
  {
    "ID contact":   "CONT011",
    "Famille":      "Martin",
    "ID Famille":   "FAM002",
    "Nom":          "Martin",
    "Prénom":       "Nadia",
    "Parent":       "Oui",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 21 54 87 33",
    "WhatsApp":     "06 21 54 87 33",
    "Email":        "nadia.martin@hotmail.fr",
    "Adresse":      "14 rue des Acacias",
    "Code postal":  "44100",
    "Ville":        "Nantes",
    "Date de naissance": "22/09/1983",
    "Groupe":       "A1",
    "Inscriptions": "Payé",
    "Assiduité":    82,
    "Test 1":       13,
    "Test 2":       15,
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Emma Martin — fille, bénéficiaire A1
  {
    "ID contact":   "CONT012",
    "Famille":      "Martin",
    "ID Famille":   "FAM002",
    "Nom":          "Martin",
    "Prénom":       "Emma",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 62 11 45 89",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "14 rue des Acacias",
    "Code postal":  "44100",
    "Ville":        "Nantes",
    "Date de naissance": "05/03/2010",
    "Groupe":       "A1",
    "Inscriptions": "Payé",
    "Assiduité":    91,
    "Test 1":       16,
    "Test 2":       17,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
  // Théo Martin — fils, bénéficiaire Alpha (débutant)
  {
    "ID contact":   "CONT013",
    "Famille":      "Martin",
    "ID Famille":   "FAM002",
    "Nom":          "Martin",
    "Prénom":       "Théo",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 62 11 45 89",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "14 rue des Acacias",
    "Code postal":  "44100",
    "Ville":        "Nantes",
    "Date de naissance": "18/11/2014",
    "Groupe":       "Alpha",
    "Inscriptions": "Payé",
    "Assiduité":    78,
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },

  // ── FAM003 Benali ─────────────────────────────────────────────
  // Fatima Benali — mère, OUI bénéficiaire (suit cours Pré-A1)
  {
    "ID contact":   "CONT014",
    "Famille":      "Benali",
    "ID Famille":   "FAM003",
    "Nom":          "Benali",
    "Prénom":       "Fatima",
    "Parent":       "Oui",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 33 77 52 14",
    "WhatsApp":     "06 33 77 52 14",
    "Email":        "fatima.benali@gmail.com",
    "Adresse":      "3 allée des Peupliers",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "08/06/1986",
    "Groupe":       "Pré-A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    67,
    "Test 1":       7,
    "Test 2":       9,
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Youssef Benali — père, NON bénéficiaire (travaille, pas disponible)
  {
    "ID contact":   "CONT015",
    "Famille":      "Benali",
    "ID Famille":   "FAM003",
    "Nom":          "Benali",
    "Prénom":       "Youssef",
    "Parent":       "Oui",
    "Bénéficiaire": "Non",
    "N° de téléphone": "06 33 77 52 15",
    "WhatsApp":     "06 33 77 52 15",
    "Email":        "youssef.benali@gmail.com",
    "Adresse":      "3 allée des Peupliers",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "15/02/1982",
    "Groupe":       "",
    "Inscriptions": "",
    "Assiduité":    "",
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Yasmine Benali — fille, bénéficiaire A2
  {
    "ID contact":   "CONT016",
    "Famille":      "Benali",
    "ID Famille":   "FAM003",
    "Nom":          "Benali",
    "Prénom":       "Yasmine",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 33 77 52 14",
    "WhatsApp":     "",
    "Email":        "yasmine.benali@gmail.com",
    "Adresse":      "3 allée des Peupliers",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "12/07/2008",
    "Groupe":       "A2",
    "Inscriptions": "Exonéré",
    "Assiduité":    88,
    "Test 1":       17,
    "Test 2":       18,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
  // Amine Benali — fils, bénéficiaire A1
  {
    "ID contact":   "CONT017",
    "Famille":      "Benali",
    "ID Famille":   "FAM003",
    "Nom":          "Benali",
    "Prénom":       "Amine",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 33 77 52 14",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "3 allée des Peupliers",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "30/01/2012",
    "Groupe":       "A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    72,
    "Test 1":       11,
    "Test 2":       13,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Non",
  },

  // ── FAM004 Nguyen ─────────────────────────────────────────────
  // Linh Nguyen — mère, OUI bénéficiaire (suit cours A2, très assidue)
  {
    "ID contact":   "CONT018",
    "Famille":      "Nguyen",
    "ID Famille":   "FAM004",
    "Nom":          "Nguyen",
    "Prénom":       "Linh",
    "Parent":       "Oui",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 88 23 04 61",
    "WhatsApp":     "07 88 23 04 61",
    "Email":        "linh.nguyen@gmail.com",
    "Adresse":      "8 boulevard Michelet",
    "Code postal":  "44200",
    "Ville":        "Nantes",
    "Date de naissance": "03/12/1990",
    "Groupe":       "A2",
    "Inscriptions": "Payé",
    "Assiduité":    95,
    "Test 1":       18,
    "Test 2":       19,
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Nathan Nguyen — fils, bénéficiaire A1
  {
    "ID contact":   "CONT019",
    "Famille":      "Nguyen",
    "ID Famille":   "FAM004",
    "Nom":          "Nguyen",
    "Prénom":       "Nathan",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 88 23 04 61",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "8 boulevard Michelet",
    "Code postal":  "44200",
    "Ville":        "Nantes",
    "Date de naissance": "20/08/2011",
    "Groupe":       "A1",
    "Inscriptions": "Payé",
    "Assiduité":    84,
    "Test 1":       14,
    "Test 2":       15,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },

  // ── FAM005 Diallo ─────────────────────────────────────────────
  // Ibrahima Diallo — père, NON bénéficiaire
  {
    "ID contact":   "CONT020",
    "Famille":      "Diallo",
    "ID Famille":   "FAM005",
    "Nom":          "Diallo",
    "Prénom":       "Ibrahima",
    "Parent":       "Oui",
    "Bénéficiaire": "Non",
    "N° de téléphone": "06 51 88 39 72",
    "WhatsApp":     "06 51 88 39 72",
    "Email":        "ibrahima.diallo@gmail.com",
    "Adresse":      "27 rue du Breil",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "17/05/1977",
    "Groupe":       "",
    "Inscriptions": "",
    "Assiduité":    "",
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Aïssatou Diallo — mère, OUI bénéficiaire (suit cours Pré-A1)
  {
    "ID contact":   "CONT021",
    "Famille":      "Diallo",
    "ID Famille":   "FAM005",
    "Nom":          "Diallo",
    "Prénom":       "Aïssatou",
    "Parent":       "Oui",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 51 88 39 73",
    "WhatsApp":     "06 51 88 39 73",
    "Email":        "aissatou.diallo@gmail.com",
    "Adresse":      "27 rue du Breil",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "02/03/1981",
    "Groupe":       "Pré-A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    58,
    "Test 1":       6,
    "Test 2":       8,
    "Autorisation parentale": "",
    "Droit à l'image": "Non",
  },
  // Mariama Diallo — fille, bénéficiaire A1
  {
    "ID contact":   "CONT022",
    "Famille":      "Diallo",
    "ID Famille":   "FAM005",
    "Nom":          "Diallo",
    "Prénom":       "Mariama",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 51 88 39 72",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "27 rue du Breil",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "11/04/2009",
    "Groupe":       "A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    76,
    "Test 1":       12,
    "Test 2":       14,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
  // Saliou Diallo — fils, bénéficiaire Pré-A1
  {
    "ID contact":   "CONT023",
    "Famille":      "Diallo",
    "ID Famille":   "FAM005",
    "Nom":          "Diallo",
    "Prénom":       "Saliou",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 51 88 39 72",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "27 rue du Breil",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "27/09/2012",
    "Groupe":       "Pré-A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    44,
    "Test 1":       5,
    "Test 2":       7,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
  // Fatoumata Diallo — fille, bénéficiaire Alpha (débutante)
  {
    "ID contact":   "CONT024",
    "Famille":      "Diallo",
    "ID Famille":   "FAM005",
    "Nom":          "Diallo",
    "Prénom":       "Fatoumata",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 51 88 39 72",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "27 rue du Breil",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "04/02/2016",
    "Groupe":       "Alpha",
    "Inscriptions": "Exonéré",
    "Assiduité":    90,
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "NON",
    "Droit à l'image": "Oui",
  },

  // ── FAM006 Rousseau ───────────────────────────────────────────
  // Claire Rousseau — mère seule, NON bénéficiaire (pas le temps)
  {
    "ID contact":   "CONT025",
    "Famille":      "Rousseau",
    "ID Famille":   "FAM006",
    "Nom":          "Rousseau",
    "Prénom":       "Claire",
    "Parent":       "Oui",
    "Bénéficiaire": "Non",
    "N° de téléphone": "07 14 56 83 20",
    "WhatsApp":     "07 14 56 83 20",
    "Email":        "c.rousseau.nantes@gmail.com",
    "Adresse":      "5 impasse des Lilas",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "30/11/1987",
    "Groupe":       "",
    "Inscriptions": "",
    "Assiduité":    "",
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "",
    "Droit à l'image": "Oui",
  },
  // Zoé Rousseau — fille, bénéficiaire A2
  {
    "ID contact":   "CONT026",
    "Famille":      "Rousseau",
    "ID Famille":   "FAM006",
    "Nom":          "Rousseau",
    "Prénom":       "Zoé",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 14 56 83 20",
    "WhatsApp":     "",
    "Email":        "zoe.rousseau@gmail.com",
    "Adresse":      "5 impasse des Lilas",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "16/06/2007",
    "Groupe":       "A2",
    "Inscriptions": "À payer",
    "Assiduité":    63,
    "Test 1":       14,
    "Test 2":       "",
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
  // Maxime Rousseau — fils, bénéficiaire A1
  {
    "ID contact":   "CONT027",
    "Famille":      "Rousseau",
    "ID Famille":   "FAM006",
    "Nom":          "Rousseau",
    "Prénom":       "Maxime",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "07 14 56 83 20",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "5 impasse des Lilas",
    "Code postal":  "44000",
    "Ville":        "Nantes",
    "Date de naissance": "09/08/2010",
    "Groupe":       "A1",
    "Inscriptions": "À payer",
    "Assiduité":    50,
    "Test 1":       9,
    "Test 2":       10,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },

  // ── FAM007 Okafor ─────────────────────────────────────────────
  // Chioma Okafor — mère, OUI bénéficiaire (suit cours Alpha, débutante)
  {
    "ID contact":   "CONT028",
    "Famille":      "Okafor",
    "ID Famille":   "FAM007",
    "Nom":          "Okafor",
    "Prénom":       "Chioma",
    "Parent":       "Oui",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 70 44 19 35",
    "WhatsApp":     "06 70 44 19 35",
    "Email":        "chioma.okafor@gmail.com",
    "Adresse":      "19 avenue de la Beaujoire",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "25/10/1991",
    "Groupe":       "Alpha",
    "Inscriptions": "Exonéré",
    "Assiduité":    88,
    "Test 1":       "",
    "Test 2":       "",
    "Autorisation parentale": "",
    "Droit à l'image": "Non",
  },
  // Emeka Okafor — fils, bénéficiaire A1
  {
    "ID contact":   "CONT029",
    "Famille":      "Okafor",
    "ID Famille":   "FAM007",
    "Nom":          "Okafor",
    "Prénom":       "Emeka",
    "Parent":       "Non",
    "Bénéficiaire": "Oui",
    "N° de téléphone": "06 70 44 19 35",
    "WhatsApp":     "",
    "Email":        "",
    "Adresse":      "19 avenue de la Beaujoire",
    "Code postal":  "44300",
    "Ville":        "Nantes",
    "Date de naissance": "14/05/2013",
    "Groupe":       "A1",
    "Inscriptions": "Exonéré",
    "Assiduité":    81,
    "Test 1":       13,
    "Test 2":       14,
    "Autorisation parentale": "OUI",
    "Droit à l'image": "Oui",
  },
]

// ──────────────────────────────────────────────────────────────────
//  MAIN
// ──────────────────────────────────────────────────────────────────
console.log("\n🌱  Injection des données dans Google Sheets…\n")

console.log("📂  Familles (6)")
for (const f of familles) {
  await create("Famille", f)
}

console.log("\n👤  Contacts (20)")
for (const c of contacts) {
  await create("Contact", c)
}

console.log("\n✅  Terminé — " + (familles.length + contacts.length) + " enregistrements créés")
